
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/Users/tlohr/Documents/projects/hackathon-june-2026/b2c/cartridges/plugin_abandon_cart/metadata/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface SitePreferences {
			/**
			* Abandon Cart - Enabled

				Enables the abandon cart integration with Salesforce Core. Set to true to activate API calls on checkout email submission and order placement.
			* 
			* @source [attribute](file:///Users/tlohr/Documents/projects/hackathon-june-2026/b2c/cartridges/plugin_abandon_cart/metadata/meta/system-objecttype-extensions.xml#5) 
			*/
			abandonCartEnabled: boolean | null;

			/**
			* Abandon Cart - API Path

				REST API path on Salesforce Core for the abandon cart endpoint (e.g. /services/apexrest/abandonedcart). The base URL is configured in the B2C Service Framework under abandon.cart.api credentials.
			* 
			* @source [attribute](file:///Users/tlohr/Documents/projects/hackathon-june-2026/b2c/cartridges/plugin_abandon_cart/metadata/meta/system-objecttype-extensions.xml#13) 
			*/
			abandonCartApiPath: string | null;

		}
		interface Order {
			/**
			* Original Basket UUID

				The UUID of the basket from which this order was created. Used to correlate the placed order with the abandon cart Lead in Salesforce Core.
			* 
			* @source [attribute](file:///Users/tlohr/Documents/projects/hackathon-june-2026/b2c/cartridges/plugin_abandon_cart/metadata/meta/system-objecttype-extensions.xml#25) 
			*/
			originalBasketUUID: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Abandon Cart - Enabled

				Enables the abandon cart integration with Salesforce Core. Set to true to activate API calls on checkout email submission and order placement.
			* 
			* @source [attribute](file:///Users/tlohr/Documents/projects/hackathon-june-2026/b2c/cartridges/plugin_abandon_cart/metadata/meta/system-objecttype-extensions.xml#5) 
			*/
			(name: 'abandonCartEnabled'): boolean | null;
			
			/**
			* Abandon Cart - API Path

				REST API path on Salesforce Core for the abandon cart endpoint (e.g. /services/apexrest/abandonedcart). The base URL is configured in the B2C Service Framework under abandon.cart.api credentials.
			* 
			* @source [attribute](file:///Users/tlohr/Documents/projects/hackathon-june-2026/b2c/cartridges/plugin_abandon_cart/metadata/meta/system-objecttype-extensions.xml#13) 
			*/
			(name: 'abandonCartApiPath'): string | null;
			
	}
}