name: Build

on: push

jobs:
    deploy-build:
        uses: ./.github/workflows/plugin-build.yml
        with:
            NODE_VERSION: 24.6
        secrets:
            GH_TOKEN: ${{ secrets.SFRA_ACCESS_TOKEN }}
